### ISSUE TITLE
optional resolve

### ISSUE THREAD

**Issue by fljot** [Kukkimonsuta/inversify-react#10]
What do you think about having `@optional` in addition to `@resolve`? https://github.com/inversify/InversifyJS/blob/master/wiki/optional_dependencies.md

Maybe in React world it would be easier to have single decorator for this, e.g. `@optionalResolve`?

**Comment by Kukkimonsuta** [comment]
Sounds like reasonable addition, I'm thinking `@resolve.optional` would be good to match `@provide.singleton` etc. I'm currently on vacation, so I'll take a look once I come back. PRs are also welcome - there isn't much to it, inversify does all the heavy lifting, we just forward some calls.

**Comment by Kukkimonsuta** [comment]
Implemented as `resolve.optional` and `resolve.optional(serviceIdentifier, defaultValue?)`. Published on npm as 0.4.0

**Comment by fljot** [comment]
@Kukkimonsuta man, golden. Do you like beer, can I send you some from my land?)
-> email/telegram/twitter?

**Comment by Kukkimonsuta** [comment]
@fljot Thank you, that's very generous of you, but really not necessary :)

https://twitter.com/the_kukki
