### ISSUE TITLE
Error on npm install after 0.4.2

### ISSUE THREAD

**Issue by jjavierdguezas** [Kukkimonsuta/inversify-react#12]
I think this error was introduced after #11 
after updating to version `0.4.2` every time I run `npm install` this error is thrown:
```shell
$ npm install
npm ERR! code EISGIT
npm ERR! path C:\root\TTMS\DevOpsTest\WebTemplate\node_modules\inversify-react
npm ERR! git C:\root\TTMS\DevOpsTest\WebTemplate\node_modules\inversify-react: Appears to be a git repo or submodule.
npm ERR! git     C:\root\TTMS\DevOpsTest\WebTemplate\node_modules\inversify-react
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

Reading about this on other project issues it seems that a `.git` folder is included and it shouldn't

Deleting `.git` folder in `~/node_modules/inversify-react` solves this issue

**Comment by Kukkimonsuta** [comment]
It seems npm includes `.git/hooks/README.sample` due to whitelist having higher priority than blacklisted `.git`.

Should be fixed in 0.4.3: https://unpkg.com/browse/inversify-react@0.4.3/
