### ISSUE TITLE
Didn't work with react 18

### ISSUE THREAD

**Issue by AndreiDavidchyk** [Kukkimonsuta/inversify-react#15]
As I understand, ProviderProps must have a children property:
children?: React.ReactNode

See details: https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc

TS2322: Type '{ children: Element; container: Container; }' is not assignable to type 'IntrinsicAttributes & Readonly<{ container: Container | (() => Container); standalone?: boolean; }>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Readonly<{ container: Container | (() => Container); standalone?: boolean; }>'.
     96 |             const subDomain = locationProvider.getSubDomain();
     97 |             return (
  >  98 |                 <Provider container={this.container}>
        |                  ^^^^^^^^
     99 |                     <PointPageRender domain={subDomain} path={window.location.pathname} />
    100 |                 </Provider>
    101 |             );

**Comment by AndreiDavidchyk** [comment]
Sorry for bad error text
![image](https://user-images.githubusercontent.com/101095441/163129489-c61f226c-612d-403e-93c5-5cf0a70c9492.png)

**Comment by Kukkimonsuta** [comment]
https://www.npmjs.com/package/inversify-react

Should be fixed in 1.0.2, please reopen if it didn't help.
