### ISSUE TITLE
Add support for multiInject in class components

### ISSUE THREAD

**Issue by dominic-simplan** [Kukkimonsuta/inversify-react#17]
As far as I can see, multiInject currently only works in hooks with `useAllInjections`.

When trying to use `@resolve` in a class component for a serviceIdentifier which has multiple concretions bound, I am getting the following error: `Ambiguous match found for serviceIdentifier`. I would expect it to return an array of all bound concretions.

Is this not implemented yet or am i doing something wrong?

**Comment by Kukkimonsuta** [comment]
Added `resolve.all` and `resolve.optional.all` and released as v1.1.0

https://github.com/Kukkimonsuta/inversify-react#resolveall

**Comment by dominic-simplan** [comment]
Thank you, that was extremely fast! :)
