### ISSUE TITLE
using inversify-inject-decorators

### ISSUE THREAD

**Issue by veeramarni** [Kukkimonsuta/inversify-react#5]
Based on inversify documents, it is recommended to use `inversify-inject-decorators` for property injection in react properties. Do you think you see a need for this package?

**Comment by Kukkimonsuta** [comment]
`inversify-inject-decorators` are bound to specific instance of a container, whereas this project uses reacts context to flow the container (and child containers) with the component tree. This allows you to create universal component that pulls services from `inversify` and allows reuse across different projects.

`inversify-inject-decorators` is more complete and more universal, whereas `inversify-react` serves more specific use. I believe they can coexist quite peacefully :)

**Comment by veeramarni** [comment]
@Kukkimonsuta thanks for your response.
