### ISSUE TITLE
SSR "window is not defined"

### ISSUE THREAD

**Issue by t-l-k** [Kukkimonsuta/inversify-react#8]
This component is suffering the same Webpack problem as detailed over at https://github.com/webpack/webpack/issues/6522 - when running in a server side render function there is a `ReferenceError: window is not defined` error. 

I've patched a local build of this module in my workspace by building it with the following additional `output` entry in `tsconfig.json`:

```js
globalObject: `(typeof self !== 'undefined' ? self : this)`
```

Thanks

**Comment by Kukkimonsuta** [comment]
Thank you for the report and solution. I've released new version `0.2.7` that should have this issue fixed.
